name: backend

on:
  push:
    paths:
    - "CMakeLists.txt"
    - "src/*"
  pull_request:
    paths:
    - "CMakeLists.txt"
    - "src/*"

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        lws-version: [3.2.0, 3.1.0, 2.4.2]
    steps:
      - name: install apt packages
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake libjson-c-dev libssl-dev libuv1-dev
      - name: compile libwebsockets-${{ matrix.lws-version }} from source
        env:
          LWS_VERSION: ${{ matrix.lws-version }}
        run: |
          cd $(mktemp -d)
          curl -sLo- https://github.com/warmcat/libwebsockets/archive/v${LWS_VERSION}.tar.gz | tar xz
          cd libwebsockets-${LWS_VERSION}
          cmake -DLWS_WITH_LIBUV=ON -DLWS_UNIX_SOCK=ON -DLWS_IPV6=ON -DLWS_WITHOUT_TESTAPPS=ON -DCMAKE_BUILD_TYPE=RELEASE .
          make && sudo make install && sudo ldconfig
      - uses: actions/checkout@v1
      - name: build ttyd
        run: |
          cmake -DCMAKE_BUILD_TYPE=RELEASE .
          make && sudo make install
          ttyd -v
  cross:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        arch: [i386, x86_64, arm, armhf, mips, mipsel]
    steps:
      - uses: actions/checkout@v1
      - name: cross build (${{ matrix.arch }})
        env:
          ARCH: ${{ matrix.arch }}
        run: docker run --rm -v $(pwd):/ttyd -w /ttyd tsl0922/musl-cross ./scripts/cross-build.sh $ARCH
      - uses: actions/upload-artifact@v1
        with:
          name: ttyd.${{ matrix.arch }}
          path: build/ttyd
