name: release

on:
  push:
    tags:
    - "*"

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Build Release
        run: |
          mkdir -p bin
          for arch in i386 x86_64 arm armhf mips mipsel; do
            docker run --rm -v $(pwd):/ttyd -w /ttyd tsl0922/musl-cross ./scripts/cross-build.sh $arch
            cp build/ttyd bin/ttyd.$arch
          done
      - uses: ncipollo/release-action@v1
        with:
          artifact: "bin/*"
          token: ${{ secrets.GITHUB_TOKEN }}
